server.port=8082
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true

spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=5

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

gateway-service.uuid=${GATEWAY_SERVICE_UUID}
booking-service.uuid=${BOOKING_SERVICE_UUID}

privateKey=${JWT_PRIVATE_KEY_VALUE}

publicKey=${JWT_PUBLIC_KEY_VALUE}
