apiVersion: v1
data:
  BOOKING_SERVICE_UUID: UkVEQUNURUQ=
  GATEWAY_SERVICE_UUID: UkVEQUNURUQ=
  JWT_PRIVATE_KEY_VALUE: UkVEQUNURUQ=
  JWT_PUBLIC_KEY_VALUE: UkVEQUNURUQ=
  POSTGRES_PASSWORD: UkVEQUNURUQ=
  POSTGRES_USER: UkVEQUNURUQ=
  RABBIT_MQ_PASSWORD: UkVEQUNURUQ=
  RABBIT_MQ_USER: UkVEQUNURUQ=
kind: Secret
metadata:
  name: app-secrets
