apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: session-service }
  template:
    metadata:
      labels: { app: session-service }
    spec:
      containers:
      - name: session-service
        image: session-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef: { name: app-config }
        - secretRef: { name: app-secrets }
        env:
        - name: POSTGRES_DB
          value: "users_db"
        - name: JAVA_TOOL_OPTIONS
          value: "-Xmx256m -Xms128m -XX:MaxMetaspaceSize=128m"
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  type: NodePort
  selector: { app: session-service }
  ports:
  - port: 8081
    targetPort: 8081
